# Generated by Django 5.2 on 2025-04-21 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("start_date", models.CharField(blank=True, max_length=50)),
                ("end_date", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="parser.linkedinprofile",
                    ),
                ),
            ],
        ),
    ]
