# Generated by Django 5.2 on 2025-04-22 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser", "0002_jobexperience"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("base_url", models.URLField()),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("greenhouse", "Greenhouse"),
                            ("lever", "Lever"),
                            ("icims", "iCIMS"),
                            ("workday", "Workday"),
                            ("workable", "Workable"),
                            ("smartrecruiters", "SmartRecruiters"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserJobPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_titles",
                    models.TextField(help_text="Comma-separated list of job titles"),
                ),
                (
                    "locations",
                    models.TextField(
                        help_text="Comma-separated list of cities or states"
                    ),
                ),
                ("radius_miles", models.IntegerField(default=25)),
                ("sources", models.ManyToManyField(to="parser.jobsource")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
