# Generated by Django 5.2 on 2025-04-22 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser", "0003_jobsource_userjobpreference"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                ("internal_id", models.CharField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("url", models.URLField()),
                ("description", models.TextField(blank=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("times_seen", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parser.jobsource",
                    ),
                ),
            ],
        ),
    ]
