# Generated by Django 5.2 on 2025-04-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser", "0004_joblisting"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobsource",
            old_name="source_type",
            new_name="scraper_key",
        ),
        migrations.AddField(
            model_name="jobsource",
            name="category",
            field=models.CharField(
                blank=True,
                help_text="Optional: Job Board, Company Site, etc.",
                max_length=100,
            ),
        ),
    ]
