# Generated by Django 5.2 on 2025-04-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="headline",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="customuser",
            name="linkedin_url",
            field=models.URLField(blank=True),
        ),
    ]
